# Data

In [1]:
from IPython.display import clear_output

from djimaging.user.alpha.utils import database

# Choose indicator by uncommenting one of the following lines
indicator = 'calcium'
#indicator = 'glutamate'

database.connect_dj(indicator=indicator)
clear_output()

In [2]:
df_cell_ids = database.get_location_tab().fetch(format='frame').reset_index().loc[:,
              ['date', 'exp_num', 'group']].drop_duplicates()
df_cell_ids.to_csv(f'df_cell_ids_{indicator}.csv', index=False)

In [3]:
df_cell_ids

          date  exp_num group
0   2018-06-10        1     d
3   2020-05-10        1     d
10  2020-05-10        2     d
14  2020-05-11        1     t
20  2020-05-11        2     t
25  2020-06-07        1     d
31  2020-06-08        1     n
37  2020-06-08        2     n
42  2020-06-21        1     n
47  2020-07-05        2     d
51  2020-07-08        1     n
58  2020-07-13        1     t
66  2020-08-23        1     t
71  2020-08-24        1     t
75  2020-08-24        2     t
79  2020-08-29        1     n
83  2020-08-31        1     n